export const fileTableConfig = [
  {
    name: 'John Doe',
    action: 'update',
    fileName: 'Report.jpeg',
    description: 'Report File',
    size: '6mb',
    date: '',
  },
  {
    name: 'Beth Kim',
    action: 'update',
    fileName: 'Officer.png',
    description: 'Officer Picture',
    size: '3mb',
    date: 'Jan 25, 2026',
  },
  {
    name: 'Gilbert Batongbakal',
    action: 'update',
    fileName: 'File 1',
    description: 'Announcement File',
    size: '5mb',
    date: 'Jan 22, 2026',
  },
  {
    name: 'Dublas Kirby',
    action: 'update',
    fileName: 'File 2',
    description: 'Empty File',
    size: '0kb',
    date: 'Jan 20, 2026',
  },
  {
    name: 'Maria Aguilar',
    action: 'update',
    fileName: 'File 2',
    description: 'Empty File',
    size: '0kb',
    date: 'Jan 20, 2026',
  },
  {
    name: 'Stephen King',
    action: 'update',
    fileName: 'File 2',
    description: 'Empty File',
    size: '0kb',
    date: 'Jan 20, 2026',
  },
  {
    name: 'Jersie Tan',
    action: 'update',
    fileName: 'Report.jpeg',
    description: 'Report File',
    size: '6mb',
    date: '',
  },
  {
    name: 'Joyce Bernal',
    action: 'update',
    fileName: 'Officer.png',
    description: 'Officer Picture',
    size: '3mb',
    date: 'Jan 25, 2026',
  },
  {
    name: 'Eiriel Kim',
    action: 'update',
    fileName: 'File 1',
    description: 'Announcement File',
    size: '5mb',
    date: 'Jan 22, 2026',
  },
  {
    name: 'Junior Sanchez',
    action: 'update',
    fileName: 'File 2',
    description: 'Empty File',
    size: '0kb',
    date: 'Jan 20, 2026',
  },
  {
    name: 'Patrick Star',
    action: 'update',
    fileName: 'File 2',
    description: 'Empty File',
    size: '0kb',
    date: 'Jan 20, 2026',
  },
  {
    name: 'Anthony Squarepants',
    action: 'update',
    fileName: 'File 2',
    description: 'Empty File',
    size: '0kb',
    date: 'Jan 20, 2026',
  },
];
